### ISSUE TITLE
[bug] Docker logs emit invalid JSON with nested double quotes and braces

### ISSUE THREAD

**Issue by trallnag** [mendhak/docker-http-https-echo#10]
Hey @mendhak, something messes with the escaping of the payloads and makes the logged JSON invalid. Here is the emitted log:

```
httpecho_1      | -----------------
httpecho_1      | { path: '/',
httpecho_1      |   headers:
httpecho_1      |    { host: 'httpecho:8888',
httpecho_1      |      'user-agent': 'Alertmanager/0.21.0',
httpecho_1      |      'content-length': '905',
httpecho_1      |      'content-type': 'application/json' },
httpecho_1      |   method: 'POST',
httpecho_1      |   body: '{"receiver":"generic","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"WhatEver","foo_bar_qux":"foo_moo_zoom","severity":"warning"},"annotations":{"description":"A Prometheus job has disappeared\\\\n  VALUE = 2\\\\n  LABELS: map[]","summary":"Prometheus job missing (instance )"},"startsAt":"2020-11-03T17:09:36.14925565Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://9e6d80bea9ef:9090/graph?g0.expr=vector%282%29+%3E+vector%281%29\\u0026g0.tab=1","fingerprint":"d57ff78af6ac95e8"}],"groupLabels":{"alertname":"WhatEver"},"commonLabels":{"alertname":"WhatEver","foo_bar_qux":"foo_moo_zoom","severity":"warning"},"commonAnnotations":{"description":"A Prometheus job has disappeared\\\\n  VALUE = 2\\\\n  LABELS: map[]","summary":"Prometheus job missing (instance )"},"externalURL":"http://1217896f2a1d:9093","version":"4","groupKey":"{}:{alertname=\\"WhatEver\\"}","truncatedAlerts":0}\n',
httpecho_1      |   cookies: undefined,
httpecho_1      |   fresh: false,
httpecho_1      |   hostname: 'httpecho',
httpecho_1      |   ip: '::ffff:172.18.0.3',
httpecho_1      |   ips: [],
httpecho_1      |   protocol: 'http',
httpecho_1      |   query: {},
httpecho_1      |   subdomains: [],
httpecho_1      |   xhr: false,
httpecho_1      |   os: { hostname: '1b549382c54e' },
httpecho_1      |   connection: { servername: undefined } }
httpecho_1      | ::ffff:172.18.0.3 - - [03/Nov/2020:17:10:06 +0000] "POST / HTTP/1.1" 200 1451 "-" "Alertmanager/0.21.0"
```

If you go ahead and copy paste the payload body into a validator you will get an error.

```
Parse error on line 35:
...":"{}:{alertname=\\"WhatEver\\"}",  "tr
-----------------------^
Expecting 'EOF', '}', ':', ',', ']', got 'undefined'
```

Is this expected or fixable? Or is there another way to get the "real" payload? I want to use your docker image to get payloads for testing stuff

If you want to reproduce my setup simply run `docker-compose up` with the set of files attached in the zip. You will have to wait 2 minutes for the request to arrive

[docker-compose.zip](https://github.com/mendhak/docker-http-https-echo/files/5482995/docker-compose.zip)

---

Here is the payload I would expect:

```json
{
  "receiver": "generic",
  "status": "firing",
  "alerts": [
    {
      "status": "firing",
      "labels": {
        "alertname": "WhatEver",
        "foo_bar_qux": "foo_moo_zoom",
        "severity": "warning"
      },
      "annotations": {
        "description": "A Prometheus job has disappeared\\n  VALUE = 2\\n  LABELS: map[]",
        "summary": "Prometheus job missing (instance )"
      },
      "startsAt": "2020-11-03T17:51:36.14925565Z",
      "endsAt": "0001-01-01T00:00:00Z",
      "generatorURL": "http://9e6d80bea9ef:9090/graph?g0.expr=vector%282%29+%3E+vector%281%29&g0.tab=1",
      "fingerprint": "d57ff78af6ac95e8"
    }
  ],
  "groupLabels": {
    "alertname": "WhatEver"
  },
  "commonLabels": {
    "alertname": "WhatEver",
    "foo_bar_qux": "foo_moo_zoom",
    "severity": "warning"
  },
  "commonAnnotations": {
    "description": "A Prometheus job has disappeared\\n  VALUE = 2\\n  LABELS: map[]",
    "summary": "Prometheus job missing (instance )"
  },
  "externalURL": "http://1217896f2a1d:9093",
  "version": "4",
  "groupKey": "{}:{alertname=\"WhatEver\"}",
  "truncatedAlerts": 0
}
```

**Comment by mendhak** [comment]
I think if I'm understanding this correctly, what you're actually asking for is the body to be parsed as JSON you can look at, if the content type passed in is JSON.  So to escape it and show it as an object, just as part of the rest of the response.  

Yes I think this is possible.  I wouldn't touch the `body` though - as that's reflecting what was passed in.  

What I can do is: if the Content-Type is application/json, I can add a `.json` property which will contain the nested object.

**Comment by mendhak** [comment]
Example output. Notice the `"json"` property.  The output still wasn't passing jsonlint.com validation and I realized, JSON requires quoted keys.  So notice that all the keys in the output are quoted now.  

    httpecho_1      | -----------------
    httpecho_1      | {
    httpecho_1      |     "path": "/",
    httpecho_1      |     "headers": {
    httpecho_1      |         "host": "httpecho:8888",
    httpecho_1      |         "user-agent": "Alertmanager/0.21.0",
    httpecho_1      |         "content-length": "905",
    httpecho_1      |         "content-type": "application/json"
    httpecho_1      |     },
    httpecho_1      |     "method": "POST",
    httpecho_1      |     "body": "{\"receiver\":\"generic\",\"status\":\"firing\",\"alerts\":[{\"status\":\"firing\",\"labels\":{\"alertname\":\"WhatEver\",\"foo_bar_qux\":\"foo_moo_zoom\",\"severity\":\"warning\"},\"annotations\":{\"description\":\"A Prometheus job has disappeared\\\\n  VALUE = 2\\\\n  LABELS: map[]\",\"summary\":\"Prometheus job missing (instance )\"},\"startsAt\":\"2020-11-03T20:48:06.14925565Z\",\"endsAt\":\"0001-01-01T00:00:00Z\",\"generatorURL\":\"http://a413d934596f:9090/graph?g0.expr=vector%282%29+%3E+vector%281%29\\u0026g0.tab=1\",\"fingerprint\":\"d57ff78af6ac95e8\"}],\"groupLabels\":{\"alertname\":\"WhatEver\"},\"commonLabels\":{\"alertname\":\"WhatEver\",\"foo_bar_qux\":\"foo_moo_zoom\",\"severity\":\"warning\"},\"commonAnnotations\":{\"description\":\"A Prometheus job has disappeared\\\\n  VALUE = 2\\\\n  LABELS: map[]\",\"summary\":\"Prometheus job missing (instance )\"},\"externalURL\":\"http://b0834199a15d:9093\",\"version\":\"4\",\"groupKey\":\"{}:{alertname=\\\"WhatEver\\\"}\",\"truncatedAlerts\":0}\n",
    httpecho_1      |     "fresh": false,
    httpecho_1      |     "hostname": "httpecho",
    httpecho_1      |     "ip": "::ffff:172.19.0.3",
    httpecho_1      |     "ips": [],
    httpecho_1      |     "protocol": "http",
    httpecho_1      |     "query": {},
    httpecho_1      |     "subdomains": [],
    httpecho_1      |     "xhr": false,
    httpecho_1      |     "os": {
    httpecho_1      |         "hostname": "a15bbc8033d1"
    httpecho_1      |     },
    httpecho_1      |     "connection": {},
    httpecho_1      |     "json": {
    httpecho_1      |         "receiver": "generic",
    httpecho_1      |         "status": "firing",
    httpecho_1      |         "alerts": [
    httpecho_1      |             {
    httpecho_1      |                 "status": "firing",
    httpecho_1      |                 "labels": {
    httpecho_1      |                     "alertname": "WhatEver",
    httpecho_1      |                     "foo_bar_qux": "foo_moo_zoom",
    httpecho_1      |                     "severity": "warning"
    httpecho_1      |                 },
    httpecho_1      |                 "annotations": {
    httpecho_1      |                     "description": "A Prometheus job has disappeared\\n  VALUE = 2\\n  LABELS: map[]",
    httpecho_1      |                     "summary": "Prometheus job missing (instance )"
    httpecho_1      |                 },
    httpecho_1      |                 "startsAt": "2020-11-03T20:48:06.14925565Z",
    httpecho_1      |                 "endsAt": "0001-01-01T00:00:00Z",
    httpecho_1      |                 "generatorURL": "http://a413d934596f:9090/graph?g0.expr=vector%282%29+%3E+vector%281%29&g0.tab=1",
    httpecho_1      |                 "fingerprint": "d57ff78af6ac95e8"
    httpecho_1      |             }
    httpecho_1      |         ],
    httpecho_1      |         "groupLabels": {
    httpecho_1      |             "alertname": "WhatEver"
    httpecho_1      |         },
    httpecho_1      |         "commonLabels": {
    httpecho_1      |             "alertname": "WhatEver",
    httpecho_1      |             "foo_bar_qux": "foo_moo_zoom",
    httpecho_1      |             "severity": "warning"
    httpecho_1      |         },
    httpecho_1      |         "commonAnnotations": {
    httpecho_1      |             "description": "A Prometheus job has disappeared\\n  VALUE = 2\\n  LABELS: map[]",
    httpecho_1      |             "summary": "Prometheus job missing (instance )"
    httpecho_1      |         },
    httpecho_1      |         "externalURL": "http://b0834199a15d:9093",
    httpecho_1      |         "version": "4",
    httpecho_1      |         "groupKey": "{}:{alertname=\"WhatEver\"}",
    httpecho_1      |         "truncatedAlerts": 0
    httpecho_1      |     }
    httpecho_1      | }
    httpecho_1      | ::ffff:172.19.0.3 - - [03/Nov/2020:20:48:36 +0000] "POST / HTTP/1.1" 200 2655 "-" "Alertmanager/0.21.0"

**Comment by mendhak** [comment]
Here is the commit.  https://github.com/mendhak/docker-http-https-echo/commit/dc3973d0884472083f4052914166bf4d64880c34

I've put a tagged image on Docker Hub.  @trallnag  Can you test out this image with tag:

    mendhak/http-https-echo:issue-10-json-payload-output

If everything's OK I can merge it later.

**Comment by trallnag** [comment]
I've tried it and it's indeed working perfectly, thanks a lot

![image](https://user-images.githubusercontent.com/24834206/98044525-54c9c800-1e27-11eb-9a08-b2a8fd995bfa.png)

**Comment by trallnag** [comment]
Also learned something new, I assumed that this "JSON-view" is the same as the raw body of the request

**Comment by mendhak** [comment]
I've merged it, so the :latest image has this change now. Cheers.
