### ISSUE TITLE
Use Github action as CI/CD

### ISSUE THREAD

**Issue by Sispheor** [mendhak/docker-http-https-echo#18]
The current "build passing" badge is actually not a CI/CD but a link to the Docker hub page.
As you've already coded some tests, you should implement Github action as CI/CD for this project.
Then protect PRs with this CI/CD.

**Comment by mendhak** [comment]
I will do this, thanks.  I've already got an issue for this, I'm thinking of combining the tests with image scanning too here:  https://github.com/mendhak/docker-http-https-echo/issues/13

Then the build passing can be meaningful.   I will close this so it can be tracked in #13.
