### ISSUE TITLE
Is there an ARM64 version of this image?

### ISSUE THREAD

**Issue by spacewander** [mendhak/docker-http-https-echo#23]
Thanks for the great project!
Is there an ARM64 version of this image?

**Comment by mendhak** [comment]
Well I had a go at this, I tried to build it via Github Actions using the [run-on-arch](https://github.com/uraimo/run-on-arch-action) action.  

https://github.com/mendhak/docker-http-https-echo/blob/testarch/.github/workflows/testarch.yml#L35

But I couldn't get it to build. I'm [not sure what I'm missing](https://github.com/mendhak/docker-http-https-echo/runs/2811309893?check_suite_focus=true#step:5:15).  It'll be useful if there are any examples I can see of other people building ARM64 docker images via Github Actions.

**Comment by kcalmond** [comment]
How about this? https://hub.docker.com/r/ealen/echo-server

**Comment by mendhak** [comment]
@kcalmond thank you that was it!  I had a look at their action and it was deprecated but I did find the [docker buildx action](https://github.com/docker/setup-buildx-action) which importantly works with [qemu](https://github.com/docker/setup-qemu-action).  This action seems to have matured relatively recently, which might explain why I could not find it back in June. 

Are you able to test it on some ARM64 device?  I have a tag to test, `issue23multi`

See: 
https://hub.docker.com/layers/mendhak/http-https-echo/issue23multi/images/sha256-508398614ac280850111433b579fceca4567bc2b8b8e04b8b6549be2ec2056c2?context=explore

**Comment by mendhak** [comment]
Oh I have a Raspberry Pi.  I tested and armv7 is working!

Does anyone have an arm64 device?

**Comment by mendhak** [comment]
I created an ARM64 VM in QEMU following these instructions:  https://gist.github.com/itzurabhi/a760155c28c0e34ebb14ccf10f08d47b

Then I was able to download and run the image.  Seems fine.
