### ISSUE TITLE
Force a request to sleep for a period of time

### ISSUE THREAD

**Issue by daninthewoods** [mendhak/docker-http-https-echo#24]
This is an awesome testing utility, thanks so much.  We use it a lot for testing our k8s proxy logic (nginx/haproxy etc.)  If it could expand to allow a custom header to cause a sleep period for a given request, it would provide the ability to also test features of proxies like request queuing and server bottlenecking.

**Comment by mendhak** [comment]
I've got a tag you can test.  `mendhak/http-https-echo:sleep-header`

Then try a curl command like this

    curl -H "x-set-response-delay-ms: 9000" http://localhost:8080/

**Comment by daninthewoods** [comment]
Perfect, that works great.  Thanks for being so responsive.

**Comment by mendhak** [comment]
OK nice I've tested a bit too, added to the test script. 

I've merged this now it's in tag 18.  

docker pull mendhak/http-https-echo:18
