### ISSUE TITLE
Consider adding an open source license?

### ISSUE THREAD

**Issue by Bobgy** [mendhak/docker-http-https-echo#27]
Hi @mendhak, this looks really nice and helpful!
I wonder if you are interested in adding an open source license, so that people can "freely" use this tool?

**Comment by mendhak** [comment]
Oops I really thought I had added one, totally forgot.  :stuck_out_tongue: 

It's added now: https://github.com/mendhak/docker-http-https-echo/blob/master/LICENSE.md

Thanks!

**Comment by Bobgy** [comment]
Thank you!
