### ISSUE TITLE
Pass response status code via query string or path

### ISSUE THREAD

**Issue by mac2000** [mendhak/docker-http-https-echo#32]
Will be nice if it will be possible to pass response code not only by HTTP headers but by query string or path

**Motivation:** at moment I'm playing with nginx ingress, in its annotations I can pass URL only nothing else 🤷‍♂️

Seems like it will require really small change [here](https://github.com/mendhak/docker-http-https-echo/blob/master/index.js#L61), something like:

```js
const setResponseStatusCode = parseInt(req.headers["x-set-response-status-code"] || req.query["x-set-response-status-code"], 10)
```

**Comment by mendhak** [comment]
Yes thanks, that was a small change.  I also added the same feature for response delay as well. 

I've got a tag if you want to test this:  `docker pull mendhak/http-https-echo:issue32-querystring`

**Comment by mac2000** [comment]
Yey, indeed it works, thank you

**Comment by mendhak** [comment]
Yeah actually I was mulling that the other day.  It'll be good to add something like "I'm listening..."

**Comment by mendhak** [comment]
Done, I've pushed tag `mendhak/http-https-echo:22` that also includes a listening message at the beginning.
