### ISSUE TITLE
Show details of incoming mTLS Authentication/Client Certificates

### ISSUE THREAD

**Issue by Okeanos** [mendhak/docker-http-https-echo#38]
First of all: Awesome project :)

I just recently stumbled across a use case where I wanted to debug a reverse proxy and see whether it properly forwards mTLS authentication/SSL client certificates correctly. However, the `http-https-echo` server doesn't say/print that information as far as I could tell. Maybe I overlooked something or used it wrong?

Output similar to this would be expected:

```json
{
  "mtls": true,
  "mtls-details": {
    "common-name": "something",
    "authority-common-name": "something else"
  }
}
```

**Comment by mendhak** [comment]
I think I was able to accomplish this https://github.com/mendhak/docker-http-https-echo/pull/44 

Can you test it? The tag is `:mtls`, to enable it you have to pass an environment variable like this

```bash
docker run -e MTLS_ENABLE=1 -p 8080:8080 -p 8443:8443 --rm -t mendhak/http-https-echo:mtls
```

I tested from curl like so

```bash
curl -sk --cert cert.pem --key privkey.pem  https://localhost:8443/test
```

**Comment by Okeanos** [comment]
This looks very much like what I wanted. Thanks a lot for that ❤️

**Comment by mendhak** [comment]
Tag `:26` has been published to Docker Hub

https://hub.docker.com/r/mendhak/http-https-echo/tags
