### ISSUE TITLE
Please handle SIG TERM correctly

### ISSUE THREAD

**Issue by AceHack** [mendhak/docker-http-https-echo#4]
Thanks.

**Comment by mendhak** [comment]
Hello
Is this the problem you're referring to?

![image](https://user-images.githubusercontent.com/746276/78797848-2dee0500-79b0-11ea-89b0-2d031077d9e2.png)

**Comment by mendhak** [comment]
I've pushed, latest image should terminate properly now

**Comment by AceHack** [comment]
The latest image does not terminate property, it hangs forever in kubernetes when trying to shut it down.  I can tell you, your upstream does handle it correctly and shuts down fine in kubernetes.  Thanks.

**Comment by mendhak** [comment]
I misread.  You said SIGTERM.  Ok reopening.

**Comment by mendhak** [comment]
OK! Have a look now, latest image should handle SIGTERM and SIGINT properly.  I tested with Ctrl+C, and `docker stop`.

**Comment by AceHack** [comment]
Works great I see the following and it shuts down quickly.  You for sure have the best echo docker container at this point.  Thanks so much for your help.

```
Got a kill signal. Trying to exit gracefully.
HTTP and HTTPS servers closed. Asking process to exit.
```
