### ISSUE TITLE
Update the version of node engine in package.json

### ISSUE THREAD

**Issue by rishabhtulsian** [mendhak/docker-http-https-echo#40]
Update the version of the node engine in package.json to 16.0.0 to avoid older vulnerable packages from being picked up in local builds

**Comment by mendhak** [comment]
@rishabhtulsian  like this?  https://github.com/mendhak/docker-http-https-echo/pull/41/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by mendhak** [comment]
[tag `:25`](https://hub.docker.com/r/mendhak/http-https-echo/tags) is released to Docker
