### ISSUE TITLE
purpose

### ISSUE THREAD

**Issue by callowaylc** [mendhak/docker-http-https-echo#5]
just curious, but is there an additional benefit in using this tool, from dev perspective, as opposed to just using netcat/socat?

```sh
$ printf "%s\n"   "HTTP/1.0 200 OK"  "" \
    | docker run -i --rm --name test -p 8080:80 alpine:3.10 nc -lp 80 &
$ echo '{ "key": "value" }' | curl -D- -d@- localhost:8080
HTTP/1.0 200 OK

POST / HTTP/1.1
Host: localhost:8080
User-Agent: curl/7.54.0
Accept: */*
Content-Length: 18
Content-Type: application/x-www-form-urlencoded

{ "key": "value" }
$ 
```

**Comment by mendhak** [comment]
It'll depend on what you're using it for.  Not every test setup will have access to nc, like mobile devices or emulators.  If you do have those tools then this is just a convenience with some pretty printing/formatting.  I use it for HTTPS/Certificate testing too.  

In some cases like closed applications, I want to issue the request and inspect it afterwards (via docker logs rather than the response)

**Comment by callowaylc** [comment]
> Not every test setup will have access to nc, like mobile devices or emulators.

I know absolutely nothing about iot, mobile, et al, so take the following as mostly ignorance: first, I was using an alpine container, purposefully here, to ensure access to netcat or preferred tooling, because my assumption was that the repo `docker-http-https-echo`, considered docker as a given dep. Second, is nodejs, as a dependency, more or less available on non-standard platforms, than netcat, socat, /dev/tcp, telnet, yada?  

What I am driving at here, is, is did you use nodejs because you like nodejs or because the tool fit your given requirements and in a way that gives an advantage over older, better established and generally more available utilities? 

That sounds more rhetorical and aggressive than intended, and tbh, I, along with everyone else gives outsized preference to the tools they like: I use shell when I shouldn't and end up with 800 line horrors that no one can read. In this case, i am honestly just curious. 

Cheers

**Comment by mendhak** [comment]
The platform tooling and availability isn't a consideration, it's simply that this image forms part of my test suite, so I go `docker-compose up -d` and everything is ready for me to run my test harnesses.  For others it will serve other troubleshooting/testing purposes and I can't speak for them. This has no advantage over other utilities, it's merely a convenience function; if something else works for you please continue using it. 

Regarding the choice of NodeJS your question is then better directed at the origin - this repo is a fork of a fork, it's not original.   I've adopted it to add additional information in the output, the docker logs, support custom TLS certificates, and share it on Docker Hub.
