### ISSUE TITLE
Provide alternate image registry to Docker Hub

### ISSUE THREAD

**Issue by bjw-s** [mendhak/docker-http-https-echo#51]
Since Docker Hub has been applying rate limits on image pulls for a while now, and their more recent move to scrap free teams I feel that Docker Hub is becoming more and more hostile towards the OSS/hobbyist community.

I would like to propose providing GitHub Container Registry as an alternative (or completely switching over to it) for the project.

Would you be open to this? If so, I'd be willing to write up a PR to implement.

**Comment by mendhak** [comment]
Oh yeah I saw that recently too. Using Github as an alternative does sound good, I don't want to switch over right away but I'd be happy to add it to the README as alternative pull. 

Sure you could do a PR,  would that be a Github Action change? 

And also what would I need to do? I don't want to be hit with a bill! If I understood [this page correctly](https://docs.github.com/en/billing/managing-billing-for-github-packages/about-billing-for-github-packages#about-billing-for-github-packages) as long as the image is under 500 MB, I'm OK right? Haha did you expect to be hit with so many questions. I've never used Github Registry before. 

I did skim the documentation and it seems Github uses 'image registry' and 'packages' interchangeably in some places. So I think once the image is published I need to go and mark it as public so it's pull-able.

**Comment by bjw-s** [comment]
No worries about the questions :) They're understandable!
The change would indeed be a modification to the existing GitHub Actions workflows.

As for the cost question: the most important bit is "GitHub Packages usage is free for public packages" :) Since this is a public project with a public package you would not incur any cost. I've been involved in a number of projects that were building/hosting many large container images (mainly https://github.com/onedr0p/containers and https://github.com/k8s-at-home/container-images) without any cost.

I'll try and create a PR somewhere today to try and get the basics up and running.

**Comment by bjw-s** [comment]
I've created a PR that should (if all goes well 😄) push the image to GHCR in addition to Docker Hub

**Comment by mendhak** [comment]
Nice, version 29 is published :  

    docker pull ghcr.io/mendhak/http-https-echo:29

Thanks for the help, I've learned quite a bit here, I can apply it to some of my other images too.

**Comment by bjw-s** [comment]
Cool, you're welcome :) Thank you for merging!
