### ISSUE TITLE
Expose prometheus/statsd metrics

### ISSUE THREAD

**Issue by mxcoder** [mendhak/docker-http-https-echo#56]
Would be amazing if this tool would support the option to expose its own metrics, like:
- uptime
- total requests
- total requests per status
- total requests per path
- requests per second
- requests per second per status
- requests per second per path
- latency (and percentiles)
I'll check how difficult would it be to do it with some exporter, but maybe someone else has an easier approach.

**Comment by mendhak** [comment]
Tag `:31` is published.  
https://hub.docker.com/r/mendhak/http-https-echo
